name: Go Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Set up Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version: "stable"

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test ./... -v

      - name: Install examples dependencies
        working-directory: examples
        run: go mod tidy

      - name: Run examples tests
        working-directory: examples
        run: go test ./... -v

      - name: golangci-lint
        uses: golangci/golangci-lint-action@9fae48acfc02a90574d7c304a1758ef9895495fa # v7
        with:
          version: v2.1
          args: --issues-exit-code=1 --timeout 5m
          only-new-issues: false

      - name: Run tests with coverage
        run: go test -coverprofile=coverage.txt

      - name: Upload results to Codecov
        uses: codecov/codecov-action@04b047e8bb82a0c002c8312c1c880fbc6a999d45 # v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
